//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.17929
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Askme {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonString() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Askme.CommonString", typeof(CommonString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приложение запущено.
        /// </summary>
        internal static string ApplicationStart {
            get {
                return ResourceManager.GetString("ApplicationStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приложение остановлено.
        /// </summary>
        internal static string ApplicationStop {
            get {
                return ResourceManager.GetString("ApplicationStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пуск.
        /// </summary>
        internal static string buttonStart {
            get {
                return ResourceManager.GetString("buttonStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стоп.
        /// </summary>
        internal static string buttonStop {
            get {
                return ResourceManager.GetString("buttonStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не сохранены внесенные данные, сохранить и продолжить выполнение?.
        /// </summary>
        internal static string ConfirmUnsafeRun {
            get {
                return ResourceManager.GetString("ConfirmUnsafeRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текущее соединение в активной тразакции, создание новой тразакции - невозможно..
        /// </summary>
        internal static string ConnectInTransaction {
            get {
                return ResourceManager.GetString("ConnectInTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Соединение с базой данных не инициализированно.
        /// </summary>
        internal static string ConnectionIsNull {
            get {
                return ResourceManager.GetString("ConnectionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap earth_arrow {
            get {
                object obj = ResourceManager.GetObject("earth_arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Е-mail успешно отправлен.
        /// </summary>
        internal static string EmailSended {
            get {
                return ResourceManager.GetString("EmailSended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество получасовок не кратно 48.
        /// </summary>
        internal static string ErrorFiderCount {
            get {
                return ResourceManager.GetString("ErrorFiderCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Возникла ошибка при конвертации данных в XML.
        /// </summary>
        internal static string ErrorOnConvertXML {
            get {
                return ResourceManager.GetString("ErrorOnConvertXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Возникла ошибка при обработке запроса.
        /// </summary>
        internal static string ErrorOnExecSQL {
            get {
                return ResourceManager.GetString("ErrorOnExecSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Возникла ошибка при отправке сообщения.
        /// </summary>
        internal static string ErrorOnMail {
            get {
                return ResourceManager.GetString("ErrorOnMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Возникла ошибка при подготовке SQL-запроса. Подробности в лог-файле.
        /// </summary>
        internal static string ErrorOnPrepareSQL {
            get {
                return ResourceManager.GetString("ErrorOnPrepareSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Возникла ошибка при подготовке и отправке сообщения. Подробности в лог-файле.
        /// </summary>
        internal static string ErrorOnRun {
            get {
                return ResourceManager.GetString("ErrorOnRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cервер запущен.
        /// </summary>
        internal static string labelStart {
            get {
                return ResourceManager.GetString("labelStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В настоящий момент сервер остановлен.
        /// </summary>
        internal static string labelStop {
            get {
                return ResourceManager.GetString("labelStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка открытия лог-файла.
        ///Код ошибки: 
        ///{0}.
        /// </summary>
        internal static string LogOpenFailed {
            get {
                return ResourceManager.GetString("LogOpenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все файлы|*.*|Файлы Excel|*.xlsx.
        /// </summary>
        internal static string openFilterExcel {
            get {
                return ResourceManager.GetString("openFilterExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Все файлы|*.*|Файлы XSLT|*.xlt.
        /// </summary>
        internal static string openFilterXSLT {
            get {
                return ResourceManager.GetString("openFilterXSLT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не инициализирован параметр..
        /// </summary>
        internal static string ParamIsNull {
            get {
                return ResourceManager.GetString("ParamIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка открытия итогового файла xml.
        /// </summary>
        internal static string ResultOpenFailed {
            get {
                return ResourceManager.GetString("ResultOpenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Состояние: формирование XML.
        /// </summary>
        internal static string stateConvertXML {
            get {
                return ResourceManager.GetString("stateConvertXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Состояние: выполнение запроса SQL.
        /// </summary>
        internal static string stateGetSQL {
            get {
                return ResourceManager.GetString("stateGetSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Состояние: подготовка запроса.
        /// </summary>
        internal static string statePrepareSQL {
            get {
                return ResourceManager.GetString("statePrepareSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Состояние: отправка e-mail.
        /// </summary>
        internal static string stateSendMail {
            get {
                return ResourceManager.GetString("stateSendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Состояние: ожидание.
        /// </summary>
        internal static string stateWait {
            get {
                return ResourceManager.GetString("stateWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Соединение не установлено. 
        ///Код ошибки: &quot;{0}&quot;.
        /// </summary>
        internal static string TestConnectionFailed {
            get {
                return ResourceManager.GetString("TestConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Соединение успешно установлено..
        /// </summary>
        internal static string TestConnectionOk {
            get {
                return ResourceManager.GetString("TestConnectionOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Транзакия не инициализированна..
        /// </summary>
        internal static string TransactionIsNull {
            get {
                return ResourceManager.GetString("TransactionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка при открытии файла содержащего итоговый xml.
        ///Подробности в логе..
        /// </summary>
        internal static string XmlFileOpenFailed {
            get {
                return ResourceManager.GetString("XmlFileOpenFailed", resourceCulture);
            }
        }
    }
}
