//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Askme {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonString() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Askme.CommonString", typeof(CommonString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приложение запущено.
        /// </summary>
        internal static string ApplicationStart {
            get {
                return ResourceManager.GetString("ApplicationStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приложение остановлено.
        /// </summary>
        internal static string ApplicationStop {
            get {
                return ResourceManager.GetString("ApplicationStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пуск.
        /// </summary>
        internal static string buttonStart {
            get {
                return ResourceManager.GetString("buttonStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стоп.
        /// </summary>
        internal static string buttonStop {
            get {
                return ResourceManager.GetString("buttonStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не сохранены внесенные данные, сохранить и продолжить выполнение?.
        /// </summary>
        internal static string ConfirmUnsafeRun {
            get {
                return ResourceManager.GetString("ConfirmUnsafeRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущее соединение в активной тразакции, создание новой тразакции - невозможно..
        /// </summary>
        internal static string ConnectInTransaction {
            get {
                return ResourceManager.GetString("ConnectInTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Соединение с базой данных не инициализированно.
        /// </summary>
        internal static string ConnectionIsNull {
            get {
                return ResourceManager.GetString("ConnectionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Е-mail успешно отправлен.
        /// </summary>
        internal static string EmailSended {
            get {
                return ResourceManager.GetString("EmailSended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество получасовок не кратно 48.
        /// </summary>
        internal static string ErrorFiderCount {
            get {
                return ResourceManager.GetString("ErrorFiderCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возникла ошибка при конвертации данных в XML.
        /// </summary>
        internal static string ErrorOnConvertXML {
            get {
                return ResourceManager.GetString("ErrorOnConvertXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возникла ошибка при обработке запроса.
        /// </summary>
        internal static string ErrorOnExecSQL {
            get {
                return ResourceManager.GetString("ErrorOnExecSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возникла ошибка при отправке сообщения.
        /// </summary>
        internal static string ErrorOnMail {
            get {
                return ResourceManager.GetString("ErrorOnMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возникла ошибка при подготовке SQL-запроса. Подробности в лог-файле.
        /// </summary>
        internal static string ErrorOnPrepareSQL {
            get {
                return ResourceManager.GetString("ErrorOnPrepareSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возникла ошибка при подготовке и отправке сообщения. Подробности в лог-файле.
        /// </summary>
        internal static string ErrorOnRun {
            get {
                return ResourceManager.GetString("ErrorOnRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cервер запущен.
        /// </summary>
        internal static string labelStart {
            get {
                return ResourceManager.GetString("labelStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В настоящий момент сервер остановлен.
        /// </summary>
        internal static string labelStop {
            get {
                return ResourceManager.GetString("labelStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка открытия лог-файла.
        ///Код ошибки: 
        ///{0}.
        /// </summary>
        internal static string LogOpenFailed {
            get {
                return ResourceManager.GetString("LogOpenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все файлы|*.*|Файлы Excel|*.xlsx.
        /// </summary>
        internal static string openFilterExcel {
            get {
                return ResourceManager.GetString("openFilterExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все файлы|*.*|Файлы XSLT|*.xlt.
        /// </summary>
        internal static string openFilterXSLT {
            get {
                return ResourceManager.GetString("openFilterXSLT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не инициализирован параметр..
        /// </summary>
        internal static string ParamIsNull {
            get {
                return ResourceManager.GetString("ParamIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка открытия итогового файла xml.
        /// </summary>
        internal static string ResultOpenFailed {
            get {
                return ResourceManager.GetString("ResultOpenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Состояние: формирование XML.
        /// </summary>
        internal static string stateConvertXML {
            get {
                return ResourceManager.GetString("stateConvertXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Состояние: выполнение запроса SQL.
        /// </summary>
        internal static string stateGetSQL {
            get {
                return ResourceManager.GetString("stateGetSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Состояние: подготовка запроса.
        /// </summary>
        internal static string statePrepareSQL {
            get {
                return ResourceManager.GetString("statePrepareSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Состояние: отправка e-mail.
        /// </summary>
        internal static string stateSendMail {
            get {
                return ResourceManager.GetString("stateSendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Состояние: ожидание.
        /// </summary>
        internal static string stateWait {
            get {
                return ResourceManager.GetString("stateWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Соединение не установлено. 
        ///Код ошибки: &quot;{0}&quot;.
        /// </summary>
        internal static string TestConnectionFailed {
            get {
                return ResourceManager.GetString("TestConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Соединение успешно установлено..
        /// </summary>
        internal static string TestConnectionOk {
            get {
                return ResourceManager.GetString("TestConnectionOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Транзакия не инициализированна..
        /// </summary>
        internal static string TransactionIsNull {
            get {
                return ResourceManager.GetString("TransactionIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при открытии файла содержащего итоговый xml.
        ///Подробности в логе..
        /// </summary>
        internal static string XmlFileOpenFailed {
            get {
                return ResourceManager.GetString("XmlFileOpenFailed", resourceCulture);
            }
        }
    }
}
